// constants\data.ts
import { ClipboardList, Shield, User, Wallet } from "lucide-react"

// data/districts.ts
export const districts = [
  "Burera",
  "Gakenke",
  "Gicumbi",
  "Musanze",
  "Rulindo",
  "Gasabo",
  "Kicukiro",
  "Nyarugenge",
  "Bugesera",
  "Gatsibo",
  "Kayonza",
  "Kirehe",
  "Ngoma",
  "Nyagatare",
  "Rwamagana",
  "Karongi",
  "Ngororero",
  "Nyamasheke",
  "Rubavu",
  "Rusizi",
  "Rutsiro",
  "Nyabihu",
  "Gisagara",
  "Huye",
  "Kamonyi",
  "Muhanga",
  "Nyanza",
  "Nyaruguru",
  "Ruhango",
  "Nyamagabe",
]

export const districtsObj = {
  Gasabo: { latitude: -1.9536, longitude: 30.0605 },
  Kicukiro: { latitude: -1.9819, longitude: 30.1008 },
  Nyarugenge: { latitude: -1.9706, longitude: 30.0588 },
  Bugesera: { latitude: -2.2789, longitude: 30.1219 },
  Gatsibo: { latitude: -1.5847, longitude: 30.4133 },
  Kayonza: { latitude: -1.8833, longitude: 30.5333 },
  Kirehe: { latitude: -2.2667, longitude: 30.7167 },
  Ngoma: { latitude: -2.15, longitude: 30.5167 },
  Nyagatare: { latitude: -1.2981, longitude: 30.3314 },
  Rwamagana: { latitude: -1.9486, longitude: 30.4344 },
  Burera: { latitude: -1.4833, longitude: 29.8833 },
  Gakenke: { latitude: -1.6833, longitude: 29.7833 },
  Gicumbi: { latitude: -1.5833, longitude: 30.0667 },
  Musanze: { latitude: -1.4994, longitude: 29.635 },
  Rulindo: { latitude: -1.7667, longitude: 30.0833 },
  Gisagara: { latitude: -2.5667, longitude: 29.85 },
  Huye: { latitude: -2.5967, longitude: 29.7389 },
  Kamonyi: { latitude: -2.0333, longitude: 29.8833 },
  Muhanga: { latitude: -2.0833, longitude: 29.75 },
  Nyamagabe: { latitude: -2.4833, longitude: 29.4833 },
  Nyanza: { latitude: -2.35, longitude: 29.75 },
  Nyaruguru: { latitude: -2.7333, longitude: 29.4333 },
  Ruhango: { latitude: -2.2333, longitude: 29.7833 },
  Karongi: { latitude: -2.0, longitude: 29.3667 },
  Ngororero: { latitude: -1.8167, longitude: 29.5667 },
  Nyabihu: { latitude: -1.65, longitude: 29.4167 },
  Nyamasheke: { latitude: -2.3667, longitude: 29.1333 },
  Rubavu: { latitude: -1.6758, longitude: 29.2603 },
  Rusizi: { latitude: -2.4833, longitude: 28.9 },
  Rutsiro: { latitude: -1.9667, longitude: 29.3333 },
}

export const provinceMap: Record<keyof typeof districtsObj, string> = {
  Gasabo: "Kigali City",
  Kicukiro: "Kigali City",
  Nyarugenge: "Kigali City",
  Bugesera: "Eastern Province",
  Gatsibo: "Eastern Province",
  Kayonza: "Eastern Province",
  Kirehe: "Eastern Province",
  Ngoma: "Eastern Province",
  Nyagatare: "Eastern Province",
  Rwamagana: "Eastern Province",
  Burera: "Northern Province",
  Gakenke: "Northern Province",
  Gicumbi: "Northern Province",
  Musanze: "Northern Province",
  Rulindo: "Northern Province",
  Gisagara: "Southern Province",
  Huye: "Southern Province",
  Kamonyi: "Southern Province",
  Muhanga: "Southern Province",
  Nyamagabe: "Southern Province",
  Nyanza: "Southern Province",
  Nyaruguru: "Southern Province",
  Ruhango: "Southern Province",
  Karongi: "Western Province",
  Ngororero: "Western Province",
  Nyabihu: "Western Province",
  Nyamasheke: "Western Province",
  Rubavu: "Western Province",
  Rusizi: "Western Province",
  Rutsiro: "Western Province",
} as const

export const RWANDA_DISTRICTS = [
  "Burera",
  "Gakenke",
  "Gicumbi",
  "Musanze",
  "Rulindo",
  "Gasabo",
  "Kicukiro",
  "Nyarugenge",
  "Bugesera",
  "Gatsibo",
  "Kayonza",
  "Kirehe",
  "Ngoma",
  "Nyagatare",
  "Rwamagana",
  "Karongi",
  "Ngororero",
  "Nyamasheke",
  "Rubavu",
  "Rusizi",
  "Rutsiro",
  "Nyabihu",
  "Gisagara",
  "Huye",
  "Kamonyi",
  "Muhanga",
  "Nyanza",
  "Nyaruguru",
  "Ruhango",
  "Nyamagabe",
]

export const demoAccounts = [
  {
    role: "member",
    email: "member@trustlinkgroup.rw",
    icon: User,
    color: "from-green-500 to-emerald-600",
    bgColor: "bg-green-50 dark:bg-green-950/20",
    textColor: "text-green-700 dark:text-green-400",
  },
  {
    role: "Treasurer",
    email: "treasurer@trustlinkgroup.rw",
    icon: Wallet,
    color: "from-amber-500 to-orange-600",
    bgColor: "bg-amber-50 dark:bg-amber-950/20",
    textColor: "text-amber-700 dark:text-amber-400",
  },
  {
    role: "Secretary",
    email: "secretary@trustlinkgroup.rw",
    icon: ClipboardList,
    color: "from-blue-500 to-cyan-600",
    bgColor: "bg-blue-50 dark:bg-blue-950/20",
    textColor: "text-blue-700 dark:text-blue-400",
  },
  {
    role: "Admin",
    email: "admin@trustlinkgroup.rw",
    icon: Shield,
    color: "from-purple-500 to-pink-600",
    bgColor: "bg-purple-50 dark:bg-purple-950/20",
    textColor: "text-purple-700 dark:text-purple-400",
  },
]
